models/Student.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "student".
 *
 * @property int $id
 * @property string $firstname student firstname
 * @property string $lastname student lastname
 * @property string $gender student firstname
 * @property string $address student home address
 * @property string $city student home city
 * @property string $Phone parent phone
 */
class Student extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'student';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['id'], 'required',"message"=>"Nomor induk siswa harus diisi."],
            [['id'], 'unique',"message"=>"Nomor induk siswa sudah ada."],
            [['id'], 'string', 'length'=>4,"message"=>"Nomor induk siswa harus 8 digit."],
            [['firstname', 'gender'], 'required'],
            [['city'],'required',"message"=>"kota harus diisi."],
            [['firstname', 'lastname', 'gender', 'address', 'city'], 'string', 'max' => 255],
            [['Phone'], 'string', 'max' => 20],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'NIS',
            'firstname' => 'Nama Depan',
            'lastname' => 'Nama Belakang',
            'gender' => 'Gender',
            'address' => 'Alamat',
            'city' => 'Kota',
            'Phone' => 'Phone',
        ];
    }

    public function getClass()
    {
        $class= $this->hasOne(Classinfo ::className(), ['id' => 'classid'])
        ->viaTable(StudentClass::tableName(), ["studentid"=>'id']);
        return $class;
    }
}

controllers/MultimediaController.php
<?php
namespace app\controllers;
use Yii;
use app\models\Student;
use yii\helpers\Html;
use yii\helpers\FileHelper;

use yii\imagine\Image;

class MultimediaController extends \yii\web\Controller
{
    /**
     * render profile picture
     */
    public function  actionProfilePicture($id)
    {
        //create the path;
        $picturefile  = FileHelper::normalizePath( Yii::getAlias("@multimedia").
                         "/profile-picture/" . $id .".jpg");
        if (!file_exists($picturefile)){
            $picturefile  = FileHelper::normalizePath(  Yii::getAlias("@multimedia").
            "/profile-picture/default-profile.jpg");
        }
       
        $image = Image::getImagine();
        $image->open ($picturefile)
            ->show("jpg");
                     
        exit;


    }
}

controllers/StudentController.php
<?php

namespace app\controllers;

use app\models\Student;
use Yii;
use yii\base\DynamicModel;
use yii\bootstrap4\ActiveForm;
use yii\helpers\Html;

class StudentController extends \yii\web\Controller
{
    public function actionIndex($id)
    {
        $model = Student::findOne($id);
        if (is_null($model)) {
            return $this->render("notfound", ['id' => $id]);
        }
        return $this->render('index', ["model" => $model]);
    }

    public function actionCreate(){
        $model = new Student;
        if (Yii::$app->request->isAjax && Yii::$app->request->isPost) {
            $model->load(Yii::$app->request->post());
            return $this->saveStudentData($model);
        }
        return $this->render('create', ["model" => $model]);
    }
    public function actionUpdate($id)
    {
        $model = Student::findOne($id);

        if (Yii::$app->request->isAjax && Yii::$app->request->isPost) {
            //$model=NULL;
            if (is_null($model)) {
                $model = new Student;
                $properties = [];
                foreach ($model as $key => $value) {
                    $properties[] = "student-" . strtolower($key);
                }
                $properties[] = "error";
                $returnvalue = new DynamicModel($properties);
                foreach ($returnvalue as $key => $value) {
                    $returnvalue[$key] = [""];
                }
                $returnvalue->error = "Data tidak dapat diupdate. Kemungkinan data telah dihapus!<br/>" . 
                    Html::a("Refresh halaman ini", ["student/update","id"=>$id]) .
                    " untuk melihat ketersediaan data.";
                return $this->asJson($returnvalue);
            };
            $model->load(Yii::$app->request->post());
          return $this->saveStudentData($model);
        }

        if (is_null($model)) {
            return $this->render("notfound", ['id' => $id]);
        }
        return $this->render("update", ["model" => $model]);

    }

    private function saveStudentData($model)
    {
        $returnvalue = [];
     
        if ($model->validate()) {
            $model->save();

        } else {
            $returnvalue = ActiveForm::validate($model);
        }

        return $this->asJson($returnvalue);
    }
}

views/student/_form.php
<?php

use yii\bootstrap4\ActiveForm;
use yii\bootstrap4\Button;
use yii\helpers\Html;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $model app\models\Student */
/* @var $form ActiveForm */

function inputSize($size = 'medium')
{
    $css = 'col-sm-2 col-md-4';
    switch ($size) {
        case "short":
            $css = "col-sm-2 col-md-2";
            break;
        case "long":
            $css = "col-sm-4 col-md-4";
        default:

    }
    return [
        'horizontalCssClasses' => [
            'wrapper' => $css,
            'label' => 'col-sm-2 col-md-2',
        ],
    ];
};
$nowrapper = [
    'horizontalCssClasses' => [
        'field' => 'col-sm-5',
    ],
    'template' => '{input}{error}{hint}',
    'options'=>["style"=>"padding-left:10px!important;"]

];

$studentClass = is_null( $model->class)?"[belum ada kelas]":$model->class->aliasshort;
$urlAction = Url::toRoute(["student/update","id"=>$model->id]);
if ($action =="create"){
    $urlAction = Url::toRoute(["student/create"]);
}
?>

        <div class="tile">
            <div class="tile-body">
                <div class="row">
                    <div class="col-sm-6 col-md-3 user">
                    <div class="profile">
                        <div class="info">
                        <?=Html::img(["/multimedia/profile-picture","id"=>$model->id],["width"=>"100px",
                        "class"=>"user-img"])?>
                            <h4><?=$model->firstname?> <?=$model->lastname?> </h4>
                            <p><?=$studentClass;?></p>
                            </div>

                        </div>
                    </div>

                    <div class="col-sm-6 col-md-9">
                        <?php $form = ActiveForm::begin(['layout' => 'horizontal',
                        'validateOnSubmit'=>true,
                        'validateOnBlur'=>false,
                        'validateOnType' =>false,
                        'validateOnChange'=>false,
                        'enableClientValidation'=>false,
                        'enableAjaxValidation'=>true,
                        'validationUrl'=>$urlAction,
                        'options'=>['autocomplete'=>"off", 'id'=>'form-data-siswa'] ]);?>

                        <?=$form->field($model, 'id',inputSize("short"))?>
                      
                        <div class="form-row mb-3">
                        <label class="col-sm-2 col-form-label" for="student-firstname">Nama Lengkap</label>
                            <?=$form->field($model, 'firstname', $nowrapper)?>
                            <?=$form->field($model, 'lastname', $nowrapper)?>
                                    
                        </div>

                            <?=$form->field($model, 'gender')->inline()->radioList(["M" => "Male", "F" => "Female"])?>
                            <?=$form->field($model, 'address')?>
                            <?=$form->field($model, 'city', inputSize("medium"))?>
                            <?=$form->field($model, 'Phone', inputSize("medium"))?>
                            <div class="form-group">
                            <?=Html::resetButton('Reset', ['class' => 'btn btn-warning']) ?>
                            <?=Html::submitButton("Simpan", ['class' => 'btn btn-success','id'=>'btnSubmit']) ?>
                            </div>
                        <?php ActiveForm::end();?>
                    </div>
                </div>
            </div>
        </div>

views/student/create.php
<?php
use app\components\Breadcrumb;

$this->registerJsFile(
    '@web/js/student/form.js',
    ['depends' => [\app\assets\AppAsset::className()]]
  );
  $this->title = "Data Siswa"
?>

<?=Breadcrumb::widget(['title'=>$this->title, 'icon'=>'fa fa-address-card-o'])?>
<?= $this->render('_form', [
    'model' => $model,
    "action"=>"create"
]) ?>

views/student/index.php
<?php
use yii\helpers\Html;
use app\components\Breadcrumb;
/* @var $this yii\web\View */
$this->title = "Data siswa";
?>
<?=Breadcrumb::widget(['title'=>$this->title, 'icon'=>'fa fa-address-card-o'])?>
<div class="row">
    <div class="col-md-12">
    <div class="tile">
        <div class="tile-body">
            <div class='row'>
                <div class="col-md-2">
                    <div class="text-center">
                    <?=Html::img(["/multimedia/profile-picture","id"=>$model->id],["width"=>"100px",
                    "class"=>"rounded mx-auto d-block"])?>
                    
                    </div>

                </div>
                <div class="col-md-10">
                    <div class="tile">
                        <div class="tile-title-w-btn">
                            <h3 class="title">Biodata</h3>
                            <p><?=Html::a("<i class='fa fa-edit'></i>Edit", 
                                            ["student/update", "id" => $model->id], 
                                            ["class" => "btn btn-primary icon-btn"]);?>
                            </p>
                        </div>
                        <div class="tile-body">
<!--a-->
                            <div class="row">
                                <div class="col-md-2"><label>NIS</label></div>
                                <div class="col-md-8"><p><?=$model->id?> </p></div>
                            </div>
                            <div class="row">
                                <div class="col-md-2"><label>Nama</label></div>
                                <div class="col-md-8"><p><?=$model->firstname?> <?=$model->lastname;?></p></div>
                            </div>
                            <div class="row">
                                <div class="col-md-2"><label>Alamat</label></div>
                                <div class="col-md-8"><p><?=$model->address?></p></div>
                            </div>
                            <div class="row">
                                <div class="col-md-2"><label>Kota</label></div>
                                <div class="col-md-8"><p><?=$model->city?></p></div>
                            </div>

<!--aend-->
                        </div>
                    </div>

                </div>
            </div>



        </div>

    </div>

    </div>
</div>

<div class="row">
    <div class="col-sm-12">
        <div class="tile">
            <div class="tile-header">
                <h3>Prestasi</h3>
            </div>
            <div class="tile-body">
                <table class="table">
                    <thead>
                        <tr>
                            <th>Tanggal</th>
                            <th>Keterangan</th>
                        </tr>
                    </thead>
                </table>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-sm-12">
        <div class="tile">
            <div class="tile-header">
                <h3>Peringatan / Hukuman</h3>
            </div>
            <div class="tile-body">
                <table class="table">
                    <thead>
                        <tr>
                            <th>Tanggal</th>
                            <th>Keterangan</th>
                        </tr>
                    </thead>
                </table>
            </div>
        </div>
    </div>
</div>

views/student/notfound.php
<?php
use app\components\Breadcrumb;
use yii\helpers\Html;
/* @var $this yii\web\View */
$this->title = "Data siswa";
?>
<?=Breadcrumb::widget(['title'=>'Data Siswa', 'icon'=>'fa fa-address-card-o'])?>


<div class="row">
    <div class="col-md-12">
        <div class="tile text-white bg-warning">
            <div class="tile-header text-center">
                <h3>Data tidak ditemukan !</h3>
            </div>
            <div  class="tile-body">
                <p> Data siswa dengan Nomor Induk Siswa <strong><?=$id;?> tidak ada.</p>
            </div>
        </div>
        
    </div>
</div>

views/student/update.php
<?php
use app\components\Breadcrumb;

$this->registerJsFile(
    '@web/js/student/form.js',
    ['depends' => [\app\assets\AppAsset::className()]]
  );
  $this->title = "Data Siswa"
?>

<?=Breadcrumb::widget(['title'=>$this->title, 'icon'=>'fa fa-address-card-o'])?>
<?= $this->render('_form', [
    'model' => $model, 
    "action"=>"update"
]) ?>