models/Classinfo.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "classinfo".
 *
 * @property string $id
 * @property string $aliasshort short name for this class
 * @property string $aliaslong long name for this class
 */
class Classinfo extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'classinfo';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['id', 'aliasshort'], 'required'],
            [['id'], 'string', 'max' => 10],
            [['aliasshort', 'aliaslong'], 'string', 'max' => 255],
            [['id'], 'unique'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'aliasshort' => 'Aliasshort',
            'aliaslong' => 'Aliaslong',
        ];
    }
}

controllers/ClassinfoController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use app\models\Classinfo;
use app\models\StudentClass;
use yii\db\Query;




class ClassinfoController extends Controller
{
    public function actionIndex()
    {
        $classinfo= Classinfo::find()->all();
        return $this->render("index",[
            "classinfo"=>$classinfo
        ]);
    }

    /**
     * get student list from class
     * return json
     */
    public function actionGetstudentlist(){
        $request = Yii::$app->request;
        $classname = $request->post("classname");
        $students = (new Query)->select('student.id, firstname, lastname, gender, address, city,phone')
        ->from ("student")
        ->innerJoin("student_class", "student_class.studentid = student.id")
        ->where (["student_class.classid"=>$classname])
        ->all();
        

        return $this->asJson($students);

    }
}

views/classinfo/index.php
<?php
use app\assets\DatatableNetAsset;
use app\components\Breadcrumb;
use yii\helpers\ArrayHelper;
use yii\helpers\Html;

DatatableNetAsset::register($this);

$this->registerJsFile(
    '@web/js/classinfo/index.js',
    ['depends' => [\app\assets\DatatableNetAsset::className()]]
);

$classinfoArray = ArrayHelper::map($classinfo, 'id', 'aliasshort');

?>
<?=Breadcrumb::widget(['title' => 'Daftar Kelas', 'icon' => 'fa fa-bar-chart'])?>
<div class="row">
  <div class="col-sm-12">
    <div class="tile">
      <div class="tile-title">Daftar Siswa Per Kelas</div>
      <div class="tile-body">
          <!--form-->
          <?=Html::beginForm(['classinfo/getstudentlist'], 'post', ["class" => "row"]);?>
                <div class="form-group col-md-3">
                    <label class="control-label">Kelas</label>
                  </div>
                  <div class="form-group col-md-3">
                    <?=Html::dropDownList("classname", null, $classinfoArray,
                         ["class" => "form-control","id"=>"classname"]);?>
                  </div>
                  <div class="form-group col-md-4 align-self-end">
                    <button class="btn btn-primary" id="btnViewClass" type="button">
                      <i class="fa fa-fw fa-lg fa-search"></i>Lihat</button>
                  </div>
          <?=Html::endForm()?>
          <form class="row">

                </form>
          <!--end form-->

      </div>
  </div>
  </div>
</div>
<div class="tile">
  <div class="tile-body">
  <div class="table-responsive">
  <table class="table table-bordered table-striped table-hover" id="studenttable">
    <caption>Daftar Siswa</caption>
      <thead>
        <tr>
          <th class="col-sm-1">NIS</th>
          <th class="col-sm-3">Nama Lengkap</th>
          <th class="col-sm-4">Alamat</th>
          <th class="col-sm-1">Gender</th>
          <th class="col-sm-1">Phone</th>

        </tr>
      </thead>
    </table>
  </div>
  
  </div>
</div>